/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.org.sesisenai.estudante.joao_luckow.desktop;

import br.org.sesisenai.estudante.joao_luckow.Main;
import br.org.sesisenai.estudante.joao_luckow.entities.Atividade;
import br.org.sesisenai.estudante.joao_luckow.entities.Turma;
import com.j256.ormlite.dao.Dao;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author joao_luckow
 */
public class ClassroomFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClassroomFrame.class.getName());
    private Turma classroom;
    /**
     * Creates new form ClassroomFrame
     */
    public ClassroomFrame(Turma classroom) {
        this.classroom = classroom;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        className = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        teacherName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        activitiesList = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        className.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        className.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        className.setText("Turma - " + classroom.getName());

        jLabel2.setText("Professor Responsável:");

        teacherName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        teacherName.setText(classroom.getTeachers().get(0).getName()
        );

        activitiesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = classroom.getActivities().stream().map((t) -> t.getId() + " - " + t.getDesc()).toList().toArray(String[]::new);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(activitiesList);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Atividades");

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("-");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(className, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(teacherName))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(className, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(teacherName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String activitiyDesc = JOptionPane.showInputDialog("Descrição da Atividade (100 caracteres)");
        classroom.createActivity(activitiyDesc);
        JOptionPane.showMessageDialog(this, "Atividade criada!");
        refreshList();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int a = JOptionPane.showConfirmDialog(this, "Você deseja deletar a atividade '"+activitiesList.getSelectedValue()+"'?", "Confirme Decisão", JOptionPane.YES_NO_OPTION, 3);
        if(a == 0) {
        Dao<Atividade, Integer> activitiesDao = Main.databaseConnection.getActivitiesDao(Main.databaseConnection.createConnection());
            try {
                activitiesDao.deleteById(Integer.parseInt(activitiesList.getSelectedValue().split("-")[0].trim()));
                refreshList();
            }catch(SQLException ex) {
                ex.printStackTrace();
            }        
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> activitiesList;
    private javax.swing.JLabel className;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel teacherName;
    // End of variables declaration//GEN-END:variables

    private void refreshList() {
        activitiesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = classroom.getActivities().stream().map((t) -> t.getId() + " - " + t.getDesc()).toList().toArray(String[]::new);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
    }
}
